### ISSUE TITLE
Support Node.js 18

### ISSUE THREAD

**Issue by oliviertassinari** [mui/tech-challenge-react#17]
Because we are using Next.js v10, candidates can't use Node.js v18 or later. The current workaround for them is to do:

```diff
diff --git a/docs/package.json b/docs/package.json
index 916e7c3..37b07ef 100644
--- a/docs/package.json
+++ b/docs/package.json
@@ -8,7 +8,7 @@
     "build": "cross-env NODE_ENV=production next build --profile",
     "build:clean": "rimraf .next && yarn build",
     "build-sw": "node ./scripts/buildServiceWorker.js",
-    "dev": "rimraf ./node_modules/.cache/babel-loader && next dev --port 3002",
+    "dev": "rimraf ./node_modules/.cache/babel-loader && NODE_OPTIONS=--openssl-legacy-provider next dev --port 3002",
     "deploy": "git push material-ui-docs next:next",
     "export": "rimraf docs/export && next export --threads=3 -o export && yarn build-sw",
     "icons": "rimraf public/static/icons/* && node ./scripts/buildIcons.js",
```

Going forward, we might have to recreate the whole https://github.com/mui/react-technical-challenge repository using the latest version of [http://github.com/mui/material-ui](https://github.com/mui/material-ui).

**Comment by mnajdova** [comment]
> Going forward, we might have to recreate the whole https://github.com/mui/react-technical-challenge repository using the latest version of [http://github.com/mui/material-ui](https://github.com/mui/material-ui).

I was thinking about the same thing today, I could open a PR for it this/next week.

**Comment by oliviertassinari** [comment]
Based on https://nodejs.org/en/about/releases/, I assume that this will really become a problem on 2022-10-25.

> Active LTS status and are ready for general use

**Comment by cherniavskii** [comment]
I've started with the latest version of monorepo in https://github.com/mui/react-technical-challenge/tree/upgrade-monorepo
It's WIP, but there are pages for both phases already.
I'm going to update the implementation of `useAutocomplete` to make sure the bug from phase 2 is reproducible there.

**Comment by oliviertassinari** [comment]
@cherniavskii Oh great initiative, I have created a separate issue for this in #28. For the Node.js version issue, there is an immediate quick win that I went after in #27.
